In [2]:
import numpy as np

In [3]:
from numpy import genfromtxt

In [4]:
fpath = ("tipsf.csv")


In [5]:
x= np.genfromtxt(fpath,delimiter =',', skip_header=True)
print(x)

[[  0.    16.99   1.01 ...   1.     0.     2.  ]
 [  1.    10.34   1.66 ...   1.     0.     3.  ]
 [  2.    21.01   3.5  ...   1.     0.     3.  ]
 ...
 [241.    22.67   2.   ...   0.     0.     2.  ]
 [242.    17.82   1.75 ...   0.     0.     2.  ]
 [243.    18.78   3.   ...   2.     0.     2.  ]]


In [6]:
np.sum(x[:,1])#total bill value


4827.77

In [7]:
np.sum(x[:,2])#total tip value

731.5799999999999

In [8]:
x[:,2]

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,

In [9]:
np.unique(x,return_index = True,return_counts = True)


(array([  0.  ,   1.  ,   1.01,   1.1 ,   1.17,   1.25,   1.32,   1.36,
          1.44,   1.45,   1.47,   1.48,   1.5 ,   1.56,   1.57,   1.58,
          1.61,   1.63,   1.64,   1.66,   1.67,   1.68,   1.71,   1.73,
          1.75,   1.76,   1.8 ,   1.83,   1.92,   1.96,   1.97,   1.98,
          2.  ,   2.01,   2.02,   2.03,   2.05,   2.09,   2.18,   2.2 ,
          2.23,   2.24,   2.3 ,   2.31,   2.34,   2.45,   2.47,   2.5 ,
          2.52,   2.54,   2.55,   2.56,   2.6 ,   2.61,   2.64,   2.71,
          2.72,   2.74,   2.75,   2.83,   2.88,   2.92,   3.  ,   3.02,
          3.06,   3.07,   3.08,   3.09,   3.11,   3.12,   3.14,   3.15,
          3.16,   3.18,   3.21,   3.23,   3.25,   3.27,   3.31,   3.35,
          3.39,   3.4 ,   3.41,   3.48,   3.5 ,   3.51,   3.55,   3.6 ,
          3.61,   3.68,   3.71,   3.75,   3.76,   3.92,   4.  ,   4.06,
          4.08,   4.19,   4.2 ,   4.29,   4.3 ,   4.34,   4.5 ,   4.67,
          4.71,   4.73,   5.  ,   5.07,   5.14,   5.15,   5.16, 

In [10]:
np.sum(x[:,4])

93.0

In [11]:
np.mean(x[:,3])#avg of male and female

0.6434426229508197

In [12]:
np.unique(x[:,5])

array([0., 1., 2., 3.])

In [13]:
np.unique(x[:,5],return_counts=True)#for no of days 

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

In [14]:
np.sum(x[:,3])

157.0

In [15]:
np.unique(x[:,3])

array([0., 1.])

In [16]:
np.unique(x[:,3],return_counts=True)

(array([0., 1.]), array([ 87, 157], dtype=int64))

In [17]:
tip=x[:,2 ]#avg tip of male and female
sex=x[:,3]
total_tip_male = np.mean(tip[sex == 0])
total_tip_female = np.mean(tip[sex == 1])
print(total_tip_male )
print(total_tip_female )


2.8334482758620685
3.0896178343949043


In [18]:
amount=x[:,1]#  total amount of male and female
sex=x[:,3]
tip=x[:,2]#avg tip of male and female
total_tip_male = np.mean(tip[sex == 0])
total_tip_female = np.mean(tip[sex == 1])
total_amount_male = np.sum(amount[sex == 0])+ np.sum(tip[sex == 0]) #amount spent by male
total_amount_female = np.sum(amount[sex == 1])+ np.sum(tip[sex == 1]) #amount spent by female
print(total_amount_male)
print(total_amount_female)



1817.4599999999996
3741.89


In [25]:
tip=np.min(x[:,2])# min value of tip
tip

1.0

In [32]:
np.max(x[:,2])# max vcalue of tip

10.0

In [40]:
lunch=x[:,6]#how many male and female are going for lunch
sex=x[:,3]
lunch_male = np.sum((sex == 0) & (lunch==0))
lunch_female = np.sum((sex == 1) & (lunch==0))
print('malecount for lunch:',lunch_male)
print('malecount for lunch:',lunch_female)

malecount for lunch: 52
malecount for lunch: 124


In [39]:
dinner=x[:,6]#how many male and female are going for dinner
sex=x[:,3]
dinner_male = np.sum((sex == 0) & (dinner==1))
dinner_female = np.sum((sex == 1) & (dinner==1))
print('malecount for dinner: ',dinner_male)
print('malecount for dinner:',dinner_female)

malecount for dinner:  35
malecount for dinner: 33


In [41]:
np.mean(x[:,7])#avg size 

2.569672131147541

In [45]:
#no ofmale and female smokers
smokers=x[:,4]
sex=x[:,3]
male_smokers=np.sum((sex==0)& (smokers == 1))
female_smokers=np.sum((sex==1)& (smokers == 1))
print('male_smokers:',male_smokers)
print('female_smokers:',female_smokers)
                    

male_smokers: 33
female_smokers: 60
